// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ACADIAHeatMap
{
    public class ACADIAHeatMapOutputs: ResultsBase
    {
		/// <summary>
		/// The vals of cells.
		/// </summary>
		[JsonProperty("Debug")]
		public string Debug {get;}



        /// <summary>
        /// Construct a ACADIAHeatMapOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ACADIAHeatMapOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a ACADIAHeatMapOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ACADIAHeatMapOutputs(string debug): base()
        {
			this.Debug = debug;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}