// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ACADIAHeatMap
{
    public class ACADIAHeatMapInputs: S3Args
    {
		/// <summary>
		/// Target size of cell.
		/// </summary>
		[JsonProperty("Cell Size")]
		public double CellSize {get;}



        /// <summary>
        /// Construct a ACADIAHeatMapInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ACADIAHeatMapInputs() : base()
        {
			this.CellSize = 10;

        }


        /// <summary>
        /// Construct a ACADIAHeatMapInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ACADIAHeatMapInputs(double cellSize, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.CellSize = cellSize;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}