// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace ACADIABeamsFromModelPoints
{
    public class ACADIABeamsFromModelPointsOutputs: ResultsBase
    {
		/// <summary>
		/// The total number of beams.
		/// </summary>
		[JsonProperty("Number of beams")]
		public double NumberOfBeams {get;}



        /// <summary>
        /// Construct a ACADIABeamsFromModelPointsOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public ACADIABeamsFromModelPointsOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a ACADIABeamsFromModelPointsOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public ACADIABeamsFromModelPointsOutputs(double numberOfBeams): base()
        {
			this.NumberOfBeams = numberOfBeams;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}